server:
  port: 8000

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        import-check:
          enabled: false
  datasource:
    driver-class-name: ${osir.datasource.driver-class-name}
    url: ${osir.datasource.url}
    username: ${osir.datasource.username}
    password: ${osir.datasource.password}

# mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.osir.takeoutpojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

# 登录相关配置
login:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${login.jwt.admin.secret-key}
    # 设置jwt过期时间
    admin-ttl: ${login.jwt.admin.ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${login.jwt.admin.token-name}
    # 用户令牌配置
    user-secret-key: ${login.jwt.user.secret-key}
    user-ttl: ${login.jwt.user.ttl}
    user-token-name: ${login.jwt.user.token-name}

# 微信相关配置
osir:
  wechat:
    appid: ${osir.wechat.appid}
    secret: ${osir.wechat.secret}

